// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjananrwqpcouywulfov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYW5hbnJ3cXBjb3V5d3VsZm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDMxNzEsImV4cCI6MjA2OTg3OTE3MX0.ubfmytEMhd5d11DbStCkcthlIrsaI9yHpIyRqdG_mLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});